/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as SignupRouteImport } from './app/routes/signup'
import { Route as ResetPasswordRouteImport } from './app/routes/reset-password'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as DashboardRouteImport } from './app/routes/dashboard'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as UsersIndexRouteImport } from './app/routes/users/index'
import { Route as ClientsIndexRouteImport } from './app/routes/clients/index'
import { Route as ClientsNewRouteImport } from './app/routes/clients/new'
import { Route as AppointmentsTodayRouteImport } from './app/routes/appointments/today'
import { Route as AppointmentsCalendarRouteImport } from './app/routes/appointments/calendar'
import { Route as AdminTagsRouteImport } from './app/routes/admin/tags'
import { Route as AdminFieldsRouteImport } from './app/routes/admin/fields'
import { Route as ClientsIdHistoryRouteImport } from './app/routes/clients/$id/history'
import { Route as ClientsIdEditRouteImport } from './app/routes/clients/$id/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsTodayRoute = AppointmentsTodayRouteImport.update({
  id: '/appointments/today',
  path: '/appointments/today',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsCalendarRoute = AppointmentsCalendarRouteImport.update({
  id: '/appointments/calendar',
  path: '/appointments/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFieldsRoute = AdminFieldsRouteImport.update({
  id: '/admin/fields',
  path: '/admin/fields',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdHistoryRoute = ClientsIdHistoryRouteImport.update({
  id: '/clients/$id/history',
  path: '/clients/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdEditRoute = ClientsIdEditRouteImport.update({
  id: '/clients/$id/edit',
  path: '/clients/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/appointments/calendar': typeof AppointmentsCalendarRoute
  '/appointments/today': typeof AppointmentsTodayRoute
  '/clients/new': typeof ClientsNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/clients/$id/edit': typeof ClientsIdEditRoute
  '/clients/$id/history': typeof ClientsIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/appointments/calendar': typeof AppointmentsCalendarRoute
  '/appointments/today': typeof AppointmentsTodayRoute
  '/clients/new': typeof ClientsNewRoute
  '/clients': typeof ClientsIndexRoute
  '/users': typeof UsersIndexRoute
  '/clients/$id/edit': typeof ClientsIdEditRoute
  '/clients/$id/history': typeof ClientsIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/appointments/calendar': typeof AppointmentsCalendarRoute
  '/appointments/today': typeof AppointmentsTodayRoute
  '/clients/new': typeof ClientsNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/clients/$id/edit': typeof ClientsIdEditRoute
  '/clients/$id/history': typeof ClientsIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/fields'
    | '/admin/tags'
    | '/appointments/calendar'
    | '/appointments/today'
    | '/clients/new'
    | '/clients/'
    | '/users/'
    | '/clients/$id/edit'
    | '/clients/$id/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/fields'
    | '/admin/tags'
    | '/appointments/calendar'
    | '/appointments/today'
    | '/clients/new'
    | '/clients'
    | '/users'
    | '/clients/$id/edit'
    | '/clients/$id/history'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/fields'
    | '/admin/tags'
    | '/appointments/calendar'
    | '/appointments/today'
    | '/clients/new'
    | '/clients/'
    | '/users/'
    | '/clients/$id/edit'
    | '/clients/$id/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AdminFieldsRoute: typeof AdminFieldsRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AppointmentsCalendarRoute: typeof AppointmentsCalendarRoute
  AppointmentsTodayRoute: typeof AppointmentsTodayRoute
  ClientsNewRoute: typeof ClientsNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ClientsIdEditRoute: typeof ClientsIdEditRoute
  ClientsIdHistoryRoute: typeof ClientsIdHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/today': {
      id: '/appointments/today'
      path: '/appointments/today'
      fullPath: '/appointments/today'
      preLoaderRoute: typeof AppointmentsTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/calendar': {
      id: '/appointments/calendar'
      path: '/appointments/calendar'
      fullPath: '/appointments/calendar'
      preLoaderRoute: typeof AppointmentsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fields': {
      id: '/admin/fields'
      path: '/admin/fields'
      fullPath: '/admin/fields'
      preLoaderRoute: typeof AdminFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id/history': {
      id: '/clients/$id/history'
      path: '/clients/$id/history'
      fullPath: '/clients/$id/history'
      preLoaderRoute: typeof ClientsIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id/edit': {
      id: '/clients/$id/edit'
      path: '/clients/$id/edit'
      fullPath: '/clients/$id/edit'
      preLoaderRoute: typeof ClientsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AdminFieldsRoute: AdminFieldsRoute,
  AdminTagsRoute: AdminTagsRoute,
  AppointmentsCalendarRoute: AppointmentsCalendarRoute,
  AppointmentsTodayRoute: AppointmentsTodayRoute,
  ClientsNewRoute: ClientsNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ClientsIdEditRoute: ClientsIdEditRoute,
  ClientsIdHistoryRoute: ClientsIdHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
