import type {
	Appointment,
	Client,
	ClientField,
	Interaction,
	Tag,
	User,
} from "@/types/common.types";

export const mockUsers: User[] = [
	{
		id: "user-1",
		name: "Maria Silva",
		email: "maria@agrobroker.com.br",
		isActive: true,
		clientCount: 25,
		pendingAppointments: 8,
		createdAt: new Date("2025-01-15"),
	},
	{
		id: "user-2",
		name: "João Santos",
		email: "joao@agrobroker.com.br",
		isActive: true,
		clientCount: 18,
		pendingAppointments: 5,
		createdAt: new Date("2025-02-20"),
	},
	{
		id: "user-3",
		name: "Ana Costa",
		email: "ana@agrobroker.com.br",
		isActive: true,
		clientCount: 32,
		pendingAppointments: 12,
		createdAt: new Date("2025-03-10"),
	},
	{
		id: "user-4",
		name: "Pedro Oliveira",
		email: "pedro@agrobroker.com.br",
		isActive: false,
		clientCount: 0,
		pendingAppointments: 0,
		createdAt: new Date("2024-11-05"),
	},
];

export const mockTags: Tag[] = [
	{
		id: "tag-1",
		name: "Grande Produtor",
		color: "#8B5CF6",
		clientCount: 12,
		createdBy: "Maria Silva",
		createdAt: new Date("2025-01-20"),
	},
	{
		id: "tag-2",
		name: "Novo Cliente",
		color: "#06B6D4",
		clientCount: 8,
		createdBy: "João Santos",
		createdAt: new Date("2025-02-15"),
	},
	{
		id: "tag-3",
		name: "Renovação",
		color: "#F59E0B",
		clientCount: 15,
		createdBy: "Maria Silva",
		createdAt: new Date("2025-01-25"),
	},
	{
		id: "tag-4",
		name: "Urgente",
		color: "#EF4444",
		clientCount: 5,
		createdBy: "Ana Costa",
		createdAt: new Date("2025-03-01"),
	},
	{
		id: "tag-5",
		name: "Soja",
		color: "#10B981",
		clientCount: 20,
		createdBy: "Maria Silva",
		createdAt: new Date("2025-01-18"),
	},
	{
		id: "tag-6",
		name: "Milho",
		color: "#EAB308",
		clientCount: 14,
		createdBy: "João Santos",
		createdAt: new Date("2025-02-10"),
	},
	{
		id: "tag-7",
		name: "Pecuária",
		color: "#92400E",
		clientCount: 18,
		createdBy: "Ana Costa",
		createdAt: new Date("2025-03-05"),
	},
	{
		id: "tag-8",
		name: "Café",
		color: "#78350F",
		clientCount: 8,
		createdBy: "Maria Silva",
		createdAt: new Date("2025-02-28"),
	},
	{
		id: "tag-9",
		name: "Pequeno Produtor",
		color: "#3B82F6",
		clientCount: 10,
		createdBy: "João Santos",
		createdAt: new Date("2025-03-15"),
	},
	{
		id: "tag-10",
		name: "Indicação",
		color: "#EC4899",
		clientCount: 6,
		createdBy: "Ana Costa",
		createdAt: new Date("2025-03-20"),
	},
];

export const mockClientFields: ClientField[] = [
	{
		id: "field-1",
		name: "Nome/Razão Social",
		type: "TEXT",
		required: true,
		isActive: true,
		order: 1,
	},
	{
		id: "field-2",
		name: "Nome da Fazenda",
		type: "TEXT",
		required: false,
		isActive: true,
		order: 2,
	},
	{
		id: "field-3",
		name: "Área Total (ha)",
		type: "NUMBER",
		required: false,
		isActive: true,
		order: 3,
	},
	{
		id: "field-4",
		name: "Município",
		type: "TEXT",
		required: false,
		isActive: true,
		order: 4,
	},
	{
		id: "field-5",
		name: "Estado",
		type: "SELECT",
		required: true,
		isActive: true,
		order: 5,
		options: ["MT", "GO", "MS", "PR", "SP", "MG", "BA", "TO", "MA", "PI"],
	},
	{
		id: "field-6",
		name: "Cultura Principal",
		type: "SELECT",
		required: false,
		isActive: true,
		order: 6,
		options: ["Soja", "Milho", "Algodão", "Café", "Cana", "Pecuária"],
	},
	{
		id: "field-7",
		name: "Safra Atual",
		type: "SELECT",
		required: false,
		isActive: true,
		order: 7,
		options: ["2025/26", "2024/25", "2023/24"],
	},
	{
		id: "field-8",
		name: "Possui Seguro Rural",
		type: "CHECKBOX",
		required: false,
		isActive: true,
		order: 8,
	},
	{
		id: "field-9",
		name: "CPF/CNPJ",
		type: "TEXT",
		required: false,
		isActive: false,
		order: 9,
	},
];

export const mockClients: Client[] = [
	{
		id: "client-1",
		whatsapp: "+5565999990001",
		notes:
			"Grande produtor de soja no MT. Interessado em seguro agrícola para safra 2025/26. Possui histórico de sinistros por seca.",
		assignedUserId: "user-1",
		assignedUserName: "Maria Silva",
		tags: [mockTags[0], mockTags[4]],
		fieldValues: [
			{
				fieldId: "field-1",
				fieldName: "Nome/Razão Social",
				fieldType: "TEXT",
				value: "José Carlos Ferreira",
			},
			{
				fieldId: "field-2",
				fieldName: "Nome da Fazenda",
				fieldType: "TEXT",
				value: "Fazenda Boa Vista",
			},
			{
				fieldId: "field-3",
				fieldName: "Área Total (ha)",
				fieldType: "NUMBER",
				value: 2500,
			},
			{
				fieldId: "field-4",
				fieldName: "Município",
				fieldType: "TEXT",
				value: "Sorriso",
			},
			{
				fieldId: "field-5",
				fieldName: "Estado",
				fieldType: "SELECT",
				value: "MT",
			},
			{
				fieldId: "field-6",
				fieldName: "Cultura Principal",
				fieldType: "SELECT",
				value: "Soja",
			},
			{
				fieldId: "field-7",
				fieldName: "Safra Atual",
				fieldType: "SELECT",
				value: "2025/26",
			},
			{
				fieldId: "field-8",
				fieldName: "Possui Seguro Rural",
				fieldType: "CHECKBOX",
				value: true,
			},
		],
		nextAppointmentDate: new Date("2026-01-31T10:00:00"),
		createdAt: new Date("2025-06-15"),
		updatedAt: new Date("2026-01-20"),
	},
	{
		id: "client-2",
		whatsapp: "+5562999990002",
		notes:
			"Pecuarista em expansão. Interessado em seguro de rebanho e penhor rural.",
		assignedUserId: "user-1",
		assignedUserName: "Maria Silva",
		tags: [mockTags[1], mockTags[6]],
		fieldValues: [
			{
				fieldId: "field-1",
				fieldName: "Nome/Razão Social",
				fieldType: "TEXT",
				value: "Agropecuária Três Irmãos Ltda",
			},
			{
				fieldId: "field-2",
				fieldName: "Nome da Fazenda",
				fieldType: "TEXT",
				value: "Fazenda Três Irmãos",
			},
			{
				fieldId: "field-3",
				fieldName: "Área Total (ha)",
				fieldType: "NUMBER",
				value: 3800,
			},
			{
				fieldId: "field-4",
				fieldName: "Município",
				fieldType: "TEXT",
				value: "Jataí",
			},
			{
				fieldId: "field-5",
				fieldName: "Estado",
				fieldType: "SELECT",
				value: "GO",
			},
			{
				fieldId: "field-6",
				fieldName: "Cultura Principal",
				fieldType: "SELECT",
				value: "Pecuária",
			},
			{
				fieldId: "field-8",
				fieldName: "Possui Seguro Rural",
				fieldType: "CHECKBOX",
				value: false,
			},
		],
		nextAppointmentDate: new Date("2026-01-31T14:30:00"),
		createdAt: new Date("2026-01-10"),
		updatedAt: new Date("2026-01-25"),
	},
	{
		id: "client-3",
		whatsapp: "+5565999990003",
		notes:
			"Renovação de apólice de seguro agrícola. Cliente desde 2020, nunca teve sinistro.",
		assignedUserId: "user-2",
		assignedUserName: "João Santos",
		tags: [mockTags[0], mockTags[2], mockTags[4], mockTags[5]],
		fieldValues: [
			{
				fieldId: "field-1",
				fieldName: "Nome/Razão Social",
				fieldType: "TEXT",
				value: "Fazendas Reunidas Almeida",
			},
			{
				fieldId: "field-2",
				fieldName: "Nome da Fazenda",
				fieldType: "TEXT",
				value: "Grupo Almeida",
			},
			{
				fieldId: "field-3",
				fieldName: "Área Total (ha)",
				fieldType: "NUMBER",
				value: 8500,
			},
			{
				fieldId: "field-4",
				fieldName: "Município",
				fieldType: "TEXT",
				value: "Lucas do Rio Verde",
			},
			{
				fieldId: "field-5",
				fieldName: "Estado",
				fieldType: "SELECT",
				value: "MT",
			},
			{
				fieldId: "field-6",
				fieldName: "Cultura Principal",
				fieldType: "SELECT",
				value: "Soja",
			},
			{
				fieldId: "field-7",
				fieldName: "Safra Atual",
				fieldType: "SELECT",
				value: "2025/26",
			},
			{
				fieldId: "field-8",
				fieldName: "Possui Seguro Rural",
				fieldType: "CHECKBOX",
				value: true,
			},
		],
		nextAppointmentDate: new Date("2026-02-01T09:00:00"),
		createdAt: new Date("2024-08-20"),
		updatedAt: new Date("2026-01-28"),
	},
	{
		id: "client-4",
		whatsapp: "+5534999990004",
		notes:
			"Cafeicultor tradicional. Primeiro contato via indicação do José Carlos.",
		assignedUserId: "user-3",
		assignedUserName: "Ana Costa",
		tags: [mockTags[1], mockTags[7], mockTags[9]],
		fieldValues: [
			{
				fieldId: "field-1",
				fieldName: "Nome/Razão Social",
				fieldType: "TEXT",
				value: "Antônio Marcos da Silva",
			},
			{
				fieldId: "field-2",
				fieldName: "Nome da Fazenda",
				fieldType: "TEXT",
				value: "Sítio São José",
			},
			{
				fieldId: "field-3",
				fieldName: "Área Total (ha)",
				fieldType: "NUMBER",
				value: 120,
			},
			{
				fieldId: "field-4",
				fieldName: "Município",
				fieldType: "TEXT",
				value: "Patrocínio",
			},
			{
				fieldId: "field-5",
				fieldName: "Estado",
				fieldType: "SELECT",
				value: "MG",
			},
			{
				fieldId: "field-6",
				fieldName: "Cultura Principal",
				fieldType: "SELECT",
				value: "Café",
			},
			{
				fieldId: "field-8",
				fieldName: "Possui Seguro Rural",
				fieldType: "CHECKBOX",
				value: false,
			},
		],
		nextAppointmentDate: new Date("2026-01-30T16:00:00"),
		createdAt: new Date("2026-01-25"),
		updatedAt: new Date("2026-01-25"),
	},
	{
		id: "client-5",
		whatsapp: "+5567999990005",
		notes:
			"Produtor de soja e milho safrinha. Urgente - prazo de contratação do Proagro vencendo.",
		assignedUserId: "user-2",
		assignedUserName: "João Santos",
		tags: [mockTags[3], mockTags[4], mockTags[5]],
		fieldValues: [
			{
				fieldId: "field-1",
				fieldName: "Nome/Razão Social",
				fieldType: "TEXT",
				value: "Pedro Henrique Martins",
			},
			{
				fieldId: "field-2",
				fieldName: "Nome da Fazenda",
				fieldType: "TEXT",
				value: "Fazenda Sol Nascente",
			},
			{
				fieldId: "field-3",
				fieldName: "Área Total (ha)",
				fieldType: "NUMBER",
				value: 1200,
			},
			{
				fieldId: "field-4",
				fieldName: "Município",
				fieldType: "TEXT",
				value: "Dourados",
			},
			{
				fieldId: "field-5",
				fieldName: "Estado",
				fieldType: "SELECT",
				value: "MS",
			},
			{
				fieldId: "field-6",
				fieldName: "Cultura Principal",
				fieldType: "SELECT",
				value: "Soja",
			},
			{
				fieldId: "field-7",
				fieldName: "Safra Atual",
				fieldType: "SELECT",
				value: "2025/26",
			},
		],
		nextAppointmentDate: new Date("2026-01-30T11:00:00"),
		createdAt: new Date("2025-12-01"),
		updatedAt: new Date("2026-01-15"),
	},
	{
		id: "client-6",
		whatsapp: "+5565999990006",
		notes:
			"Cliente fidelizada, sempre renova no início da safra. Expandiu área em 500ha.",
		assignedUserId: "user-1",
		assignedUserName: "Maria Silva",
		tags: [mockTags[0], mockTags[2], mockTags[4]],
		fieldValues: [
			{
				fieldId: "field-1",
				fieldName: "Nome/Razão Social",
				fieldType: "TEXT",
				value: "Maria Helena Rodrigues",
			},
			{
				fieldId: "field-2",
				fieldName: "Nome da Fazenda",
				fieldType: "TEXT",
				value: "Fazenda Esperança",
			},
			{
				fieldId: "field-3",
				fieldName: "Área Total (ha)",
				fieldType: "NUMBER",
				value: 1800,
			},
			{
				fieldId: "field-4",
				fieldName: "Município",
				fieldType: "TEXT",
				value: "Primavera do Leste",
			},
			{
				fieldId: "field-5",
				fieldName: "Estado",
				fieldType: "SELECT",
				value: "MT",
			},
			{
				fieldId: "field-6",
				fieldName: "Cultura Principal",
				fieldType: "SELECT",
				value: "Soja",
			},
			{
				fieldId: "field-7",
				fieldName: "Safra Atual",
				fieldType: "SELECT",
				value: "2025/26",
			},
			{
				fieldId: "field-8",
				fieldName: "Possui Seguro Rural",
				fieldType: "CHECKBOX",
				value: true,
			},
		],
		nextAppointmentDate: new Date("2026-02-03T15:00:00"),
		createdAt: new Date("2023-05-10"),
		updatedAt: new Date("2026-01-10"),
	},
	{
		id: "client-7",
		whatsapp: "+5543999990007",
		notes:
			"Pequeno produtor familiar. Aguardando documentação da DAP para enquadramento no Proagro Mais.",
		assignedUserId: "user-3",
		assignedUserName: "Ana Costa",
		tags: [mockTags[1], mockTags[8]],
		fieldValues: [
			{
				fieldId: "field-1",
				fieldName: "Nome/Razão Social",
				fieldType: "TEXT",
				value: "Ricardo Martins",
			},
			{
				fieldId: "field-2",
				fieldName: "Nome da Fazenda",
				fieldType: "TEXT",
				value: "Sítio Boa Esperança",
			},
			{
				fieldId: "field-3",
				fieldName: "Área Total (ha)",
				fieldType: "NUMBER",
				value: 45,
			},
			{
				fieldId: "field-4",
				fieldName: "Município",
				fieldType: "TEXT",
				value: "Londrina",
			},
			{
				fieldId: "field-5",
				fieldName: "Estado",
				fieldType: "SELECT",
				value: "PR",
			},
			{
				fieldId: "field-6",
				fieldName: "Cultura Principal",
				fieldType: "SELECT",
				value: "Soja",
			},
			{
				fieldId: "field-7",
				fieldName: "Safra Atual",
				fieldType: "SELECT",
				value: "2025/26",
			},
		],
		nextAppointmentDate: null,
		createdAt: new Date("2026-01-20"),
		updatedAt: new Date("2026-01-28"),
	},
	{
		id: "client-8",
		whatsapp: "+5562999990008",
		notes:
			"Cooperativa com 150 associados. Precisa de cotação para seguro coletivo agrícola.",
		assignedUserId: "user-2",
		assignedUserName: "João Santos",
		tags: [mockTags[0], mockTags[2], mockTags[4], mockTags[5]],
		fieldValues: [
			{
				fieldId: "field-1",
				fieldName: "Nome/Razão Social",
				fieldType: "TEXT",
				value: "Cooperativa Agrícola Central",
			},
			{
				fieldId: "field-2",
				fieldName: "Nome da Fazenda",
				fieldType: "TEXT",
				value: "Sede Administrativa",
			},
			{
				fieldId: "field-3",
				fieldName: "Área Total (ha)",
				fieldType: "NUMBER",
				value: 25_000,
			},
			{
				fieldId: "field-4",
				fieldName: "Município",
				fieldType: "TEXT",
				value: "Rio Verde",
			},
			{
				fieldId: "field-5",
				fieldName: "Estado",
				fieldType: "SELECT",
				value: "GO",
			},
			{
				fieldId: "field-6",
				fieldName: "Cultura Principal",
				fieldType: "SELECT",
				value: "Soja",
			},
			{
				fieldId: "field-7",
				fieldName: "Safra Atual",
				fieldType: "SELECT",
				value: "2025/26",
			},
			{
				fieldId: "field-8",
				fieldName: "Possui Seguro Rural",
				fieldType: "CHECKBOX",
				value: true,
			},
		],
		nextAppointmentDate: new Date("2026-02-05T10:30:00"),
		createdAt: new Date("2025-09-15"),
		updatedAt: new Date("2026-01-22"),
	},
];

export const mockAppointments: Appointment[] = [
	{
		id: "apt-1",
		clientId: "client-4",
		clientName: "Antônio Marcos da Silva",
		clientWhatsapp: "+5534999990004",
		clientTags: [mockTags[1], mockTags[7], mockTags[9]],
		scheduledAt: new Date("2026-01-30T16:00:00"),
		status: "OPEN",
		lastOutcome: null,
		createdAt: new Date("2026-01-25"),
	},
	{
		id: "apt-2",
		clientId: "client-5",
		clientName: "Pedro Henrique Martins",
		clientWhatsapp: "+5567999990005",
		clientTags: [mockTags[3], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-01-30T11:00:00"),
		status: "OPEN",
		lastOutcome: "Aguardando retorno sobre documentação do Proagro",
		createdAt: new Date("2026-01-15"),
	},
	{
		id: "apt-23",
		clientId: "client-5",
		clientName: "Pedro Henrique Martins",
		clientWhatsapp: "+5567999990005",
		clientTags: [mockTags[3], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-01-30T11:00:00"),
		status: "OPEN",
		lastOutcome: "Aguardando retorno sobre documentação do Proagro",
		createdAt: new Date("2026-01-15"),
	},
	{
		id: "apt-24",
		clientId: "client-5",
		clientName: "Pedro Henrique Martins",
		clientWhatsapp: "+5567999990005",
		clientTags: [mockTags[3], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-01-30T11:00:00"),
		status: "OPEN",
		lastOutcome: "Aguardando retorno sobre documentação do Proagro",
		createdAt: new Date("2026-01-15"),
	},
	{
		id: "apt-2457",
		clientId: "client-5",
		clientName: "Pedro Henrique Martins",
		clientWhatsapp: "+5567999990005",
		clientTags: [mockTags[3], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-01-30T11:00:00"),
		status: "OPEN",
		lastOutcome: "Aguardando retorno sobre documentação do Proagro",
		createdAt: new Date("2026-01-15"),
	},
	{
		id: "apt-2456",
		clientId: "client-5",
		clientName: "Pedro Henrique Martins",
		clientWhatsapp: "+5567999990005",
		clientTags: [mockTags[3], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-01-30T11:00:00"),
		status: "OPEN",
		lastOutcome: "Aguardando retorno sobre documentação do Proagro",
		createdAt: new Date("2026-01-15"),
	},
	{
		id: "apt-2455",
		clientId: "client-5",
		clientName: "Pedro Henrique Martins",
		clientWhatsapp: "+5567999990005",
		clientTags: [mockTags[3], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-01-30T11:00:00"),
		status: "OPEN",
		lastOutcome: "Aguardando retorno sobre documentação do Proagro",
		createdAt: new Date("2026-01-15"),
	},
	{
		id: "apt-2454",
		clientId: "client-5",
		clientName: "Pedro Henrique Martins",
		clientWhatsapp: "+5567999990005",
		clientTags: [mockTags[3], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-01-30T11:00:00"),
		status: "OPEN",
		lastOutcome: "Aguardando retorno sobre documentação do Proagro",
		createdAt: new Date("2026-01-15"),
	},
	{
		id: "apt-2453",
		clientId: "client-5",
		clientName: "Pedro Henrique Martins",
		clientWhatsapp: "+5567999990005",
		clientTags: [mockTags[3], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-01-30T11:00:00"),
		status: "OPEN",
		lastOutcome: "Aguardando retorno sobre documentação do Proagro",
		createdAt: new Date("2026-01-15"),
	},
	{
		id: "apt-2452",
		clientId: "client-5",
		clientName: "Pedro Henrique Martins",
		clientWhatsapp: "+5567999990005",
		clientTags: [mockTags[3], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-01-30T11:00:00"),
		status: "OPEN",
		lastOutcome: "Aguardando retorno sobre documentação do Proagro",
		createdAt: new Date("2026-01-15"),
	},
	{
		id: "apt-2451",
		clientId: "client-5",
		clientName: "Pedro Henrique Martins",
		clientWhatsapp: "+5567999990005",
		clientTags: [mockTags[3], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-01-30T11:00:00"),
		status: "OPEN",
		lastOutcome: "Aguardando retorno sobre documentação do Proagro",
		createdAt: new Date("2026-01-15"),
	},
	{
		id: "apt-3",
		clientId: "client-1",
		clientName: "José Carlos Ferreira",
		clientWhatsapp: "+5565999990001",
		clientTags: [mockTags[0], mockTags[4]],
		scheduledAt: new Date("2026-01-31T10:00:00"),
		status: "OPEN",
		lastOutcome: "Interessado em ampliar cobertura para área de milho safrinha",
		createdAt: new Date("2026-01-20"),
	},
	{
		id: "apt-4",
		clientId: "client-2",
		clientName: "Agropecuária Três Irmãos Ltda",
		clientWhatsapp: "+5562999990002",
		clientTags: [mockTags[1], mockTags[6]],
		scheduledAt: new Date("2026-01-31T14:30:00"),
		status: "OPEN",
		lastOutcome: null,
		createdAt: new Date("2026-01-25"),
	},
	{
		id: "apt-5",
		clientId: "client-3",
		clientName: "Fazendas Reunidas Almeida",
		clientWhatsapp: "+5565999990003",
		clientTags: [mockTags[0], mockTags[2], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-02-01T09:00:00"),
		status: "OPEN",
		lastOutcome: "Renovação agendada, aguardando novos valores da seguradora",
		createdAt: new Date("2026-01-28"),
	},
	{
		id: "apt-6",
		clientId: "client-6",
		clientName: "Maria Helena Rodrigues",
		clientWhatsapp: "+5565999990006",
		clientTags: [mockTags[0], mockTags[2], mockTags[4]],
		scheduledAt: new Date("2026-02-03T15:00:00"),
		status: "OPEN",
		lastOutcome: "Expansão de área confirmada, precisa atualizar apólice",
		createdAt: new Date("2026-01-10"),
	},
	{
		id: "apt-7",
		clientId: "client-8",
		clientName: "Cooperativa Agrícola Central",
		clientWhatsapp: "+5562999990008",
		clientTags: [mockTags[0], mockTags[2], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-02-05T10:30:00"),
		status: "OPEN",
		lastOutcome: "Cotação coletiva enviada, aguardando análise da diretoria",
		createdAt: new Date("2026-01-22"),
	},
	{
		id: "apt-8",
		clientId: "client-1",
		clientName: "José Carlos Ferreira",
		clientWhatsapp: "+5565999990001",
		clientTags: [mockTags[0], mockTags[4]],
		scheduledAt: new Date("2026-01-20T10:00:00"),
		status: "DONE",
		lastOutcome: "Interessado em ampliar cobertura para área de milho safrinha",
		createdAt: new Date("2026-01-10"),
	},
	{
		id: "apt-9",
		clientId: "client-3",
		clientName: "Fazendas Reunidas Almeida",
		clientWhatsapp: "+5565999990003",
		clientTags: [mockTags[0], mockTags[2], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-01-15T14:00:00"),
		status: "DONE",
		lastOutcome: "Renovação agendada, aguardando novos valores da seguradora",
		createdAt: new Date("2026-01-05"),
	},
	{
		id: "apt-10",
		clientId: "client-5",
		clientName: "Pedro Henrique Martins",
		clientWhatsapp: "+5567999990005",
		clientTags: [mockTags[3], mockTags[4], mockTags[5]],
		scheduledAt: new Date("2026-01-28T09:00:00"),
		status: "OPEN",
		lastOutcome: null,
		createdAt: new Date("2026-01-10"),
	},
	{
		id: "apt-11",
		clientId: "client-7",
		clientName: "Ricardo Martins",
		clientWhatsapp: "+5543999990007",
		clientTags: [mockTags[1], mockTags[8]],
		scheduledAt: new Date("2026-01-22T11:00:00"),
		status: "CANCELLED",
		lastOutcome: null,
		createdAt: new Date("2026-01-18"),
	},
];

export const mockInteractions: Interaction[] = [
	{
		id: "int-1",
		appointmentId: "apt-8",
		clientId: "client-1",
		userId: "user-1",
		userName: "Maria Silva",
		summary:
			"Visita técnica à Fazenda Boa Vista para avaliação da área de soja.",
		outcome:
			"Produtor interessado em incluir 800ha de milho safrinha na cobertura",
		duration: 45,
		clientSnapshot: {
			whatsapp: "+5565999990001",
			notes:
				"Grande produtor de soja no MT. Interessado em seguro agrícola para safra 2025/26.",
			tags: [mockTags[0], mockTags[4]],
			fieldValues: [
				{
					fieldId: "field-1",
					fieldName: "Nome/Razão Social",
					fieldType: "TEXT",
					value: "José Carlos Ferreira",
				},
				{
					fieldId: "field-2",
					fieldName: "Nome da Fazenda",
					fieldType: "TEXT",
					value: "Fazenda Boa Vista",
				},
				{
					fieldId: "field-5",
					fieldName: "Estado",
					fieldType: "SELECT",
					value: "MT",
				},
				{
					fieldId: "field-6",
					fieldName: "Cultura Principal",
					fieldType: "SELECT",
					value: "Soja",
				},
			],
		},
		createdAt: new Date("2026-01-20T10:45:00"),
	},
	{
		id: "int-2",
		appointmentId: "apt-9",
		clientId: "client-3",
		userId: "user-2",
		userName: "João Santos",
		summary:
			"Reunião na sede do Grupo Almeida para revisar cobertura de 8.500ha.",
		outcome:
			"Revisão completa da apólice, aguardando novos valores para safra 2025/26",
		duration: 60,
		clientSnapshot: {
			whatsapp: "+5565999990003",
			notes:
				"Renovação de apólice de seguro agrícola. Cliente desde 2020, nunca teve sinistro.",
			tags: [mockTags[0], mockTags[2], mockTags[4], mockTags[5]],
			fieldValues: [
				{
					fieldId: "field-1",
					fieldName: "Nome/Razão Social",
					fieldType: "TEXT",
					value: "Fazendas Reunidas Almeida",
				},
				{
					fieldId: "field-2",
					fieldName: "Nome da Fazenda",
					fieldType: "TEXT",
					value: "Grupo Almeida",
				},
				{
					fieldId: "field-3",
					fieldName: "Área Total (ha)",
					fieldType: "NUMBER",
					value: 8500,
				},
				{
					fieldId: "field-5",
					fieldName: "Estado",
					fieldType: "SELECT",
					value: "MT",
				},
			],
		},
		createdAt: new Date("2026-01-15T15:00:00"),
	},
	{
		id: "int-3",
		appointmentId: "apt-prev-1",
		clientId: "client-1",
		userId: "user-1",
		userName: "Maria Silva",
		summary:
			"Primeiro contato com José Carlos após indicação de outro produtor da região.",
		outcome:
			"Produtor interessado em seguro agrícola, agendada visita à fazenda",
		duration: 25,
		clientSnapshot: {
			whatsapp: "+5565999990001",
			notes: "Grande produtor de soja no MT.",
			tags: [mockTags[4]],
			fieldValues: [
				{
					fieldId: "field-1",
					fieldName: "Nome/Razão Social",
					fieldType: "TEXT",
					value: "José Carlos Ferreira",
				},
				{
					fieldId: "field-5",
					fieldName: "Estado",
					fieldType: "SELECT",
					value: "MT",
				},
			],
		},
		createdAt: new Date("2025-06-20T09:30:00"),
	},
	{
		id: "int-4",
		appointmentId: "apt-prev-2",
		clientId: "client-1",
		userId: "user-1",
		userName: "Maria Silva",
		summary: "Envio de proposta de seguro agrícola para 2.500ha de soja.",
		outcome:
			"Proposta aprovada, apólice emitida com cobertura para seca e granizo",
		duration: 35,
		clientSnapshot: {
			whatsapp: "+5565999990001",
			notes: "Grande produtor de soja no MT. Interessado em seguro agrícola.",
			tags: [mockTags[0], mockTags[4]],
			fieldValues: [
				{
					fieldId: "field-1",
					fieldName: "Nome/Razão Social",
					fieldType: "TEXT",
					value: "José Carlos Ferreira",
				},
				{
					fieldId: "field-2",
					fieldName: "Nome da Fazenda",
					fieldType: "TEXT",
					value: "Fazenda Boa Vista",
				},
				{
					fieldId: "field-3",
					fieldName: "Área Total (ha)",
					fieldType: "NUMBER",
					value: 2500,
				},
				{
					fieldId: "field-5",
					fieldName: "Estado",
					fieldType: "SELECT",
					value: "MT",
				},
			],
		},
		createdAt: new Date("2025-07-05T11:00:00"),
	},
	{
		id: "int-5",
		appointmentId: "apt-prev-3",
		clientId: "client-3",
		userId: "user-2",
		userName: "João Santos",
		summary: "Contato para início do processo de renovação da apólice.",
		outcome: "Cliente confirma interesse na renovação para safra 2025/26",
		duration: 15,
		clientSnapshot: {
			whatsapp: "+5565999990003",
			notes: "Renovação de apólice de seguro agrícola.",
			tags: [mockTags[0], mockTags[2], mockTags[4], mockTags[5]],
			fieldValues: [
				{
					fieldId: "field-1",
					fieldName: "Nome/Razão Social",
					fieldType: "TEXT",
					value: "Fazendas Reunidas Almeida",
				},
				{
					fieldId: "field-2",
					fieldName: "Nome da Fazenda",
					fieldType: "TEXT",
					value: "Grupo Almeida",
				},
				{
					fieldId: "field-5",
					fieldName: "Estado",
					fieldType: "SELECT",
					value: "MT",
				},
			],
		},
		createdAt: new Date("2026-01-05T08:30:00"),
	},
];

export function getClientName(client: Client): string {
	const nameField = client.fieldValues.find(
		(f) => f.fieldName === "Nome/Razão Social"
	);
	return (nameField?.value as string) ?? "Sem nome";
}

export function getClientsByUser(userId: string): Client[] {
	return mockClients.filter((c) => c.assignedUserId === userId);
}

export function getAppointmentsByDate(date: Date): Appointment[] {
	return mockAppointments.filter((apt) => {
		const aptDate = new Date(apt.scheduledAt);
		return (
			aptDate.getFullYear() === date.getFullYear() &&
			aptDate.getMonth() === date.getMonth() &&
			aptDate.getDate() === date.getDate()
		);
	});
}

export function getOverdueAppointments(): Appointment[] {
	const now = new Date();
	return mockAppointments.filter(
		(apt) => apt.status === "OPEN" && new Date(apt.scheduledAt) < now
	);
}

export function getInteractionsByClient(clientId: string): Interaction[] {
	return mockInteractions
		.filter((i) => i.clientId === clientId)
		.sort(
			(a, b) =>
				new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
		);
}
